apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.writer.name | default "tempo-traces-from-otel" }}
  annotations:
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default "otel-collector-sa" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRole.writer.name | default "tempo-traces-write" }}
