kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount.name | default "otel-collector-sa" }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"