apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.serviceMonitor.name | default "otel-collector-sm" }}
  annotations:
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      port: promexporter
      scheme: http
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-collector" (.Values.otelCollector.name | default "otel-collector") }}
