apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: {{ .Values.tempo.name | default "monolithic" }}
spec:
  ingestion:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
  multitenancy:
    authentication:
      - tenantId: {{ .Values.otelCollector.tenantId | default "application" }}
        tenantName: {{ .Values.otelCollector.tenantId | default "application" }}
    enabled: true
    mode: openshift
  jaegerui:
    enabled: false
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
  storage:
    traces:
      backend: memory
