---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cxfServer.name }}
  labels:
    app: {{ .Values.cxfServer.name }}
spec:
  type: {{ .Values.cxfServer.service.type }}
  ports:
    - port: {{ .Values.cxfServer.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.cxfServer.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cxfServer.name }}
  labels:
    app: {{ .Values.cxfServer.name }}
spec:
  replicas: {{ .Values.cxfServer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.cxfServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cxfServer.name }}
    spec:
      containers:
        - name: quarkus-cxf-server
          image: "{{ .Values.cxfServer.image.repository }}:{{ .Values.cxfServer.image.tag }}"
          imagePullPolicy: {{ .Values.cxfServer.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.cxfServer.livenessProbe.httpGet.path }}
              port: {{ .Values.cxfServer.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.cxfServer.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.cxfServer.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.cxfServer.readinessProbe.httpGet.path }}
              port: {{ .Values.cxfServer.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.cxfServer.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.cxfServer.readinessProbe.periodSeconds }}
          resources:
            requests:
              memory: {{ .Values.cxfServer.resources.requests.memory }}
              cpu: {{ .Values.cxfServer.resources.requests.cpu }}
            limits:
              memory: {{ .Values.cxfServer.resources.limits.memory }}
              cpu: {{ .Values.cxfServer.resources.limits.cpu }}
{{- if .Values.cxfServer.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.cxfServer.name }}
  labels:
    app: {{ .Values.cxfServer.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.cxfServer.name }}
  port:
    targetPort: http
  {{- if .Values.cxfServer.route.tls.enabled }}
  tls:
    termination: {{ .Values.cxfServer.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.cxfServer.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }}
