{{- if .Values.user.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-pguser-{{ .Values.user.name }}
  labels:
    postgres-operator.crunchydata.com/cluster: {{ .Values.cluster.name }}
    postgres-operator.crunchydata.com/pguser: {{ .Values.user.name }}
    postgres-operator.crunchydata.com/role: pguser
type: Opaque
stringData:
  password: {{ .Values.user.password | quote }}
  verifier: ""
{{- end }}
