apiVersion: v2
name: activemq-artemis
description: A Helm chart for ActiveMQ Artemis Broker on OpenShift
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - activemq
  - artemis
  - messaging
  - broker
maintainers:
  - name: Hackathon Team
