apiVersion: v1
entries:
  postgres-cluster:
  - apiVersion: v2
    appVersion: "17"
    created: "2025-12-02T10:45:03.142203115+01:00"
    description: A Helm chart for PostgreSQL Cluster using Crunchy Data Operator on
      OpenShift
    digest: 709574a731be0fbbfd878511f0e5400c92c7bbb7d0cea2608efb99fcf1e0edce
    keywords:
    - postgresql
    - postgres
    - database
    - crunchy
    maintainers:
    - name: Hackathon Team
    name: postgres-cluster
    type: application
    urls:
    - https://raw.githubusercontent.com/jboss-fuse/camel-hackathon-infra/refs/heads/main/hackathon/postgres-cluster/0.1.0/postgres-cluster-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-02T10:45:03.141882892+01:00"
