apiVersion: v1
entries:
  activemq-artemis:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-12-02T10:45:03.115135816+01:00"
    description: A Helm chart for ActiveMQ Artemis Broker on OpenShift
    digest: f7053f821fda9116df727cc1b9401738f7b3eceafaf150f24b166c42a1e37cfa
    keywords:
    - activemq
    - artemis
    - messaging
    - broker
    maintainers:
    - name: Hackathon Team
    name: activemq-artemis
    type: application
    urls:
    - https://raw.githubusercontent.com/jboss-fuse/camel-hackathon-infra/refs/heads/main/hackathon/activemq-artemis/0.1.0/activemq-artemis-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-02T10:45:03.114935919+01:00"
