apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.qdrant.name }}
  labels:
    app: {{ .Values.qdrant.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.qdrant.port }}
    targetPort: {{ .Values.qdrant.port }}
    protocol: TCP
    name: http
  - port: {{ .Values.qdrant.grpcPort }}
    targetPort: {{ .Values.qdrant.grpcPort }}
    protocol: TCP
    name: grpc
  selector:
    app: {{ .Values.qdrant.name }}
