apiVersion: v2
name: opentelemetry-infra
description: A Helm chart for OpenTelemetry stack on OpenShift
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - tempo
  - grafana
  - observability
  - tracing
  - opentelemetry
  - metrics
maintainers:
  - name: Hackathon Team
