apiVersion: v1
entries:
  tempo-monolithic:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-12-02T10:45:03.165843229+01:00"
    description: A Helm chart for Grafana Tempo Monolithic on OpenShift
    digest: efb7209c385b3e54c4ab9fe4d49af34b8fadabdde84041fd48f33ef0180d48eb
    keywords:
    - tempo
    - grafana
    - observability
    - tracing
    - opentelemetry
    maintainers:
    - name: Hackathon Team
    name: tempo-monolithic
    type: application
    urls:
    - https://raw.githubusercontent.com/jboss-fuse/camel-hackathon-infra/refs/heads/main/hackathon/tempo-monolithic/0.1.0/tempo-monolithic-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-02T10:45:03.165614095+01:00"
