apiVersion: v2
name: tempo-monolithic
description: A Helm chart for Grafana Tempo Monolithic on OpenShift
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - tempo
  - grafana
  - observability
  - tracing
  - opentelemetry
maintainers:
  - name: Hackathon Team
