apiVersion: v2
name: strimzi-cluster
description: A Helm chart for Kafka cluster using Strimzi Operator on OpenShift
type: application
version: 0.1.0
appVersion: "3.9.0"
keywords:
  - kafka
  - strimzi
  - messaging
  - streaming
  - event-driven
maintainers:
  - name: Hackathon Team
