# Default values for strimzi-cluster
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kafka:
  # Name of the Kafka cluster
  name: strimzi-cluster
  # Kafka version
  version: 4.0.0