apiVersion: v2
name: apicurio-registry
description: A Helm chart for Apicurio Registry on OpenShift
type: application
version: 0.1.0
appVersion: "2.6.13"
keywords:
  - apicurio
  - registry
  - schema
  - api
  - service-registry
maintainers:
  - name: Hackathon Team
dependencies:
  - name: postgres-cluster
    version: 0.1.0
    repository: "file://charts/postgres-cluster"
    condition: postgresql.enabled
