apiVersion: v2
name: hawtio
description: A Helm chart for deploying Hawtio Online via the Hawtio Operator
type: application
version: 0.1.0
appVersion: "2.1.0"
keywords:
  - hawtio
  - monitoring
  - management
  - jolokia
  - jmx
home: https://hawt.io
sources:
  - https://github.com/hawtio/hawtio-operator
  - https://github.com/hawtio/hawtio-online
maintainers:
  - name: Red Hat Fuse Team
